//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: public_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `PublicDataService_PublicDataServiceClient`, then call methods of this protocol to make API calls.
public protocol PublicDataService_PublicDataServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: PublicDataService_PublicDataServiceClientInterceptorFactoryProtocol? { get }

  func listExchanges(
    _ request: PublicDataService_ListExchangesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<PublicDataService_ListExchangesRequest, PublicDataService_ListExchangesResponse>

  func listCurrencies(
    _ request: PublicDataService_ListCurrenciesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<PublicDataService_ListCurrenciesRequest, PublicDataService_ListCurrenciesResponse>
}

extension PublicDataService_PublicDataServiceClientProtocol {
  public var serviceName: String {
    return "public_data_service.PublicDataService"
  }

  /// Unary call to ListExchanges
  ///
  /// - Parameters:
  ///   - request: Request to send to ListExchanges.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listExchanges(
    _ request: PublicDataService_ListExchangesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<PublicDataService_ListExchangesRequest, PublicDataService_ListExchangesResponse> {
    return self.makeUnaryCall(
      path: "/public_data_service.PublicDataService/ListExchanges",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListExchangesInterceptors() ?? []
    )
  }

  /// Unary call to ListCurrencies
  ///
  /// - Parameters:
  ///   - request: Request to send to ListCurrencies.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listCurrencies(
    _ request: PublicDataService_ListCurrenciesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<PublicDataService_ListCurrenciesRequest, PublicDataService_ListCurrenciesResponse> {
    return self.makeUnaryCall(
      path: "/public_data_service.PublicDataService/ListCurrencies",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListCurrenciesInterceptors() ?? []
    )
  }
}

public protocol PublicDataService_PublicDataServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'listExchanges'.
  func makeListExchangesInterceptors() -> [ClientInterceptor<PublicDataService_ListExchangesRequest, PublicDataService_ListExchangesResponse>]

  /// - Returns: Interceptors to use when invoking 'listCurrencies'.
  func makeListCurrenciesInterceptors() -> [ClientInterceptor<PublicDataService_ListCurrenciesRequest, PublicDataService_ListCurrenciesResponse>]
}

public final class PublicDataService_PublicDataServiceClient: PublicDataService_PublicDataServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: PublicDataService_PublicDataServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the public_data_service.PublicDataService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: PublicDataService_PublicDataServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

